var annotated_dup =
[
    [ "Appartenir", "class_appartenir.html", "class_appartenir" ],
    [ "Base_controller", "class_base__controller.html", "class_base__controller" ],
    [ "Candidature", "class_candidature.html", "class_candidature" ],
    [ "CandidatureManager", "class_candidature_manager.html", "class_candidature_manager" ],
    [ "Categorie", "class_categorie.html", "class_categorie" ],
    [ "Categorie_controller", "class_categorie__controller.html", "class_categorie__controller" ],
    [ "CategorieManager", "class_categorie_manager.html", "class_categorie_manager" ],
    [ "Droit", "class_droit.html", "class_droit" ],
    [ "Error_controller", "class_error__controller.html", "class_error__controller" ],
    [ "Manager", "class_manager.html", "class_manager" ],
    [ "Offre", "class_offre.html", "class_offre" ],
    [ "Offre_controller", "class_offre__controller.html", "class_offre__controller" ],
    [ "OffreManager", "class_offre_manager.html", "class_offre_manager" ],
    [ "Page_controller", "class_page__controller.html", "class_page__controller" ],
    [ "Photo", "class_photo.html", "class_photo" ],
    [ "Photo_controller", "class_photo__controller.html", "class_photo__controller" ],
    [ "PhotoManager", "class_photo_manager.html", "class_photo_manager" ],
    [ "ToBelongManager", "class_to_belong_manager.html", "class_to_belong_manager" ],
    [ "Utilisateur", "class_utilisateur.html", "class_utilisateur" ],
    [ "Utilisateur_controller", "class_utilisateur__controller.html", "class_utilisateur__controller" ],
    [ "UtilisateurManager", "class_utilisateur_manager.html", "class_utilisateur_manager" ],
    [ "Ville", "class_ville.html", "class_ville" ],
    [ "VilleManager", "class_ville_manager.html", "class_ville_manager" ]
];